import { Candidate } from "../types";

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: "cand-1",
    name: "Alexei Petrov",
    email: "alexei.petrov@devcraft.io",
    phone: "+1 (415) 892-3401",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Senior Distributed Systems Engineer",
    experienceYears: 7,
    location: "San Francisco, CA (Remote)",
    interviewsTaken: 3,
    lastInterviewDate: "2026-09-14",
    averageScore: 89,
    status: "Shortlisted",
    bio: "Ex-Stripe infrastructure engineer specializing in Raft consensus, Kafka pipeline optimizations, and zero-downtime database sharding.",
    skills: ["Go", "Raft Consensus", "Kafka", "Kubernetes", "Rust", "PostgreSQL"],
    strengths: [
      "Flawless understanding of distributed partition tolerances (CAP theorem)",
      "Articulate architectural trade-off communication",
      "Robust concurrent unit test methodology",
    ],
    weaknesses: [
      "Slightly slower on rapid algorithmic syntax typing under pressure",
    ],
    notes: "Top candidate for the core telemetry pipeline team. Very calm demeanor during architectural edge case drills.",
    radarScores: [
      { skill: "Distributed Architecture", score: 92, benchmark: 78 },
      { skill: "Algorithmic Efficiency", score: 85, benchmark: 72 },
      { skill: "Code Robustness", score: 90, benchmark: 76 },
      { skill: "Communication", score: 88, benchmark: 70 },
      { skill: "System Design", score: 83, benchmark: 68 },
    ],
  },
  {
    id: "cand-2",
    name: "Maya Chen",
    email: "maya.chen@alum.mit.edu",
    phone: "+1 (617) 554-9218",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Lead Full Stack Architect",
    experienceYears: 8,
    location: "Boston, MA",
    interviewsTaken: 2,
    lastInterviewDate: "2026-09-12",
    averageScore: 92,
    status: "Shortlisted",
    bio: "Staff engineer with deep expertise in Next.js Server Components, React rendering lifecycles, and high-throughput Node.js microservices.",
    skills: ["TypeScript", "Next.js", "React 19", "Node.js", "GraphQL", "Redis"],
    strengths: [
      "Exceptional mental model of React reconciliation and memory leaks",
      "High attention to web performance and Core Web Vitals",
      "Speaks with clarity and mentors while problem-solving",
    ],
    weaknesses: [
      "Prefers high-level system diagrams before writing low-level utility code",
    ],
    notes: "Demonstrated exemplary behavioral baseline consistency. Zero telemetry flags throughout 60-minute technical drill.",
    radarScores: [
      { skill: "Frontend Architecture", score: 96, benchmark: 78 },
      { skill: "Full Stack Design", score: 92, benchmark: 74 },
      { skill: "Code Speed & Quality", score: 90, benchmark: 70 },
      { skill: "Communication", score: 94, benchmark: 72 },
      { skill: "State Management", score: 95, benchmark: 75 },
    ],
  },
  {
    id: "cand-3",
    name: "Devon Thorne",
    email: "dthorne.codes@gmail.com",
    phone: "+1 (206) 438-1902",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Senior Backend Engineer (High Throughput)",
    experienceYears: 6,
    location: "Seattle, WA",
    interviewsTaken: 2,
    lastInterviewDate: "2026-09-10",
    averageScore: 74,
    status: "Under Review",
    bio: "Backend developer focused on fintech transaction engines and microservice choreography.",
    skills: ["Python", "Go", "PostgreSQL", "FastAPI", "Docker", "gRPC"],
    strengths: [
      "Good familiarity with ACID properties in distributed transactions",
    ],
    weaknesses: [
      "High code insertion variance observed during dynamic query optimization step",
      "Struggled to articulate algorithmic complexity transitions without prompts",
    ],
    notes: "Human review recommended due to correlated code insertion and external focus telemetry at minute 18.",
    radarScores: [
      { skill: "Backend Design", score: 76, benchmark: 74 },
      { skill: "Algorithmic Efficiency", score: 68, benchmark: 70 },
      { skill: "Code Robustness", score: 72, benchmark: 72 },
      { skill: "Communication", score: 70, benchmark: 68 },
      { skill: "Database Optimization", score: 82, benchmark: 75 },
    ],
  },
  {
    id: "cand-4",
    name: "Amina Al-Mansoor",
    email: "amina.mansoor@techfrontier.ae",
    phone: "+971 50 882 1943",
    avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80",
    appliedRole: "AI / ML Infrastructure Specialist",
    experienceYears: 5,
    location: "New York, NY",
    interviewsTaken: 1,
    lastInterviewDate: "2026-09-08",
    averageScore: 94,
    status: "Shortlisted",
    bio: "Specialist in large language model inference optimization, vLLM caching layers, and PyTorch kernel performance.",
    skills: ["PyTorch", "C++", "CUDA", "Python", "Triton", "Ray"],
    strengths: [
      "Deep mathematical understanding of transformer attention computation",
      "Wrote custom GPU memory paging pseudo-algorithm on whiteboard effortlessly",
    ],
    weaknesses: [
      "Niche expertise; less experienced with standard enterprise CRUD architectures",
    ],
    notes: "Outstanding technical depth. Strong candidate for LLM inference acceleration team.",
    radarScores: [
      { skill: "ML Systems", score: 98, benchmark: 75 },
      { skill: "Low-level Optimization", score: 95, benchmark: 70 },
      { skill: "Algorithmic Prowess", score: 92, benchmark: 72 },
      { skill: "Communication", score: 89, benchmark: 68 },
      { skill: "Problem Decomposition", score: 94, benchmark: 75 },
    ],
  },
  {
    id: "cand-5",
    name: "Kavita Ramachandran",
    email: "kavita.rama@protonmail.com",
    phone: "+1 (408) 723-9912",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Principal Frontend Engineer",
    experienceYears: 10,
    location: "San Jose, CA",
    interviewsTaken: 3,
    lastInterviewDate: "2026-09-05",
    averageScore: 96,
    status: "Hired",
    bio: "Design systems veteran and web performance specialist. Former core contributor to open source component libraries.",
    skills: ["React", "TypeScript", "Web Performance", "Accessibility (a11y)", "Tailwind", "WASM"],
    strengths: [
      "World-class accessibility and screen-reader keyboard interaction instincts",
      "Immediate detection of reflow/repaint bottlenecks in live coding round",
    ],
    weaknesses: [
      "High standard for perfection can occasionally slow down rapid prototyping",
    ],
    notes: "Offer extended and accepted. Outstanding scores across technical and integrity metrics.",
    radarScores: [
      { skill: "Frontend Architecture", score: 98, benchmark: 78 },
      { skill: "Accessibility & UX", score: 99, benchmark: 70 },
      { skill: "Performance Optimization", score: 94, benchmark: 74 },
      { skill: "Communication", score: 96, benchmark: 72 },
      { skill: "System Design", score: 92, benchmark: 75 },
    ],
  },
  {
    id: "cand-6",
    name: "Liam O'Connor",
    email: "liam.oconnor@dublin-eng.ie",
    phone: "+353 87 194 8201",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Senior Security & Platform Engineer",
    experienceYears: 6,
    location: "Dublin, Ireland (Remote)",
    interviewsTaken: 2,
    lastInterviewDate: "2026-09-03",
    averageScore: 85,
    status: "Shortlisted",
    bio: "Cybersecurity engineer with emphasis on zero-trust architectures, OAuth2/OIDC protocols, and container isolation.",
    skills: ["Rust", "Linux eBPF", "OAuth2", "Kubernetes Security", "Go", "Terraform"],
    strengths: [
      "Instinctive threat modeling on every architectural component",
      "Very disciplined code structure and defensive error handling",
    ],
    weaknesses: [
      "Can get bogged down in security edge cases when rapid iteration is requested",
    ],
    notes: "Excellent platform engineer. High integrity rating with completely steady behavioral baseline.",
    radarScores: [
      { skill: "Threat Modeling", score: 96, benchmark: 75 },
      { skill: "Systems Programming", score: 86, benchmark: 70 },
      { skill: "Security Standards", score: 94, benchmark: 72 },
      { skill: "Communication", score: 82, benchmark: 68 },
      { skill: "Problem Decomposition", score: 88, benchmark: 75 },
    ],
  },
  {
    id: "cand-7",
    name: "Sofia Rodriguez",
    email: "s.rodriguez@techrio.br",
    phone: "+55 21 98402 1192",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Data Platform Engineer",
    experienceYears: 4,
    location: "Austin, TX",
    interviewsTaken: 1,
    lastInterviewDate: "2026-09-01",
    averageScore: 78,
    status: "Interviewing",
    bio: "Data pipeline developer experienced in Apache Spark, dbt transformations, and Snowflake data warehouses.",
    skills: ["Python", "Apache Spark", "SQL", "Snowflake", "Kafka", "Airflow"],
    strengths: [
      "Intuitive grasp of distributed data shuffle bottlenecks",
      "Very clean SQL query dialect mastery",
    ],
    weaknesses: [
      "Less experienced with real-time stream processing compared to batch jobs",
    ],
    notes: "Scheduled for round 2 technical drill on real-time event ingestion next week.",
    radarScores: [
      { skill: "Data Pipelines", score: 85, benchmark: 74 },
      { skill: "Distributed Processing", score: 80, benchmark: 70 },
      { skill: "SQL & Query Tuning", score: 88, benchmark: 75 },
      { skill: "Communication", score: 78, benchmark: 68 },
      { skill: "Problem Decomposition", score: 76, benchmark: 72 },
    ],
  },
  {
    id: "cand-8",
    name: "Tariq Hassan",
    email: "tariq.hassan@cloudscale.net",
    phone: "+1 (312) 604-8831",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    appliedRole: "DevOps & Cloud Architect",
    experienceYears: 9,
    location: "Chicago, IL",
    interviewsTaken: 2,
    lastInterviewDate: "2026-08-28",
    averageScore: 91,
    status: "Shortlisted",
    bio: "Multi-cloud infrastructure architect focused on AWS/GCP hybrid topologies, Terraform modularity, and CI/CD resilience.",
    skills: ["Terraform", "AWS", "Kubernetes", "Helm", "ArgoCD", "Python"],
    strengths: [
      "Mastery of immutable infrastructure patterns and cost governance",
      "Clear, calm explanation style during live incident simulation",
    ],
    weaknesses: [
      "Relies on standard CLI tools rather than manual scripting for simple tasks",
    ],
    notes: "Solid candidate. High scores across behavioral baseline and architectural design.",
    radarScores: [
      { skill: "Cloud Architecture", score: 94, benchmark: 76 },
      { skill: "Infrastructure as Code", score: 95, benchmark: 72 },
      { skill: "Disaster Recovery", score: 90, benchmark: 70 },
      { skill: "Communication", score: 92, benchmark: 70 },
      { skill: "Security Hygiene", score: 88, benchmark: 74 },
    ],
  },
  {
    id: "cand-9",
    name: "Hanna Lindqvist",
    email: "hanna.l@nordictech.se",
    phone: "+46 8 721 9904",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Senior Frontend Engineer (Design Systems)",
    experienceYears: 5,
    location: "Stockholm, Sweden (Remote)",
    interviewsTaken: 1,
    lastInterviewDate: "2026-08-25",
    averageScore: 82,
    status: "Interviewing",
    bio: "Frontend engineer with an eye for micro-interactions, canvas animations, and design token architectures.",
    skills: ["React", "TypeScript", "Tailwind CSS", "Framer Motion", "Storybook", "CSS Grid"],
    strengths: [
      "Pixel-perfect CSS execution and deep knowledge of CSS grid layouts",
      "Very collaborative communication posture",
    ],
    weaknesses: [
      "Needs more practice with complex state synchronization across web workers",
    ],
    notes: "Scheduled for live coding round this afternoon.",
    radarScores: [
      { skill: "UI Architecture", score: 90, benchmark: 75 },
      { skill: "Animation & Polish", score: 92, benchmark: 68 },
      { skill: "Component Design", score: 88, benchmark: 72 },
      { skill: "Communication", score: 86, benchmark: 70 },
      { skill: "State Complexity", score: 72, benchmark: 74 },
    ],
  },
  {
    id: "cand-10",
    name: "Kenji Sato",
    email: "kenji.sato@tokyo-swe.jp",
    phone: "+81 3 5928 1093",
    avatar: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Backend & Concurrency Specialist",
    experienceYears: 7,
    location: "Tokyo, Japan (Remote)",
    interviewsTaken: 2,
    lastInterviewDate: "2026-08-20",
    averageScore: 88,
    status: "Shortlisted",
    bio: "Systems programmer specializing in lock-free data structures, actor models, and low-latency networking.",
    skills: ["C++", "Rust", "Erlang/Elixir", "Linux Socket API", "Redis", "gRPC"],
    strengths: [
      "Precise understanding of memory barriers, CAS operations, and CPU cache lines",
      "Demonstrated high integrity and natural problem formulation",
    ],
    weaknesses: [
      "Prefers lower-level problem statements to high-level product discussions",
    ],
    notes: "Strong candidate for our real-time streaming engine team.",
    radarScores: [
      { skill: "Concurrency & Lock-Free", score: 95, benchmark: 72 },
      { skill: "Memory Models", score: 94, benchmark: 70 },
      { skill: "Network Protocols", score: 88, benchmark: 74 },
      { skill: "Communication", score: 82, benchmark: 68 },
      { skill: "Decomposition", score: 86, benchmark: 75 },
    ],
  },
];
