import { Interview } from "../types";

export const MOCK_INTERVIEWS: Interview[] = [
  {
    id: "int-live-1",
    candidateId: "cand-2",
    candidateName: "Maya Chen",
    candidateEmail: "maya.chen@alum.mit.edu",
    candidateAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    jobRole: "Lead Full Stack Architect",
    interviewType: "Frontend Architecture",
    date: "2026-09-15", // Today
    time: "11:30",
    durationMinutes: 60,
    status: "Live",
    interviewerId: "usr-interviewer-1",
    interviewerName: "Marcus Sterling",
    interviewerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    token: "VT-2049-XK",
    tokenExpiresAt: "2026-09-15T13:00:00Z",
    candidateLink: "https://app.veritrust.ai/interview/VT-2049-XK",
    codingRoundConfig: {
      language: "typescript",
      starterCode: `// Problem: Optimizing React Re-renders in High-Frequency Telemetry Dashboard
import React, { useState, useEffect, useRef } from "react";

export interface TelemetryTick {
  timestamp: number;
  cpuUsage: number;
  memoryMb: number;
  anomalyDetected: boolean;
}

export function useTelemetryStream(socketUrl: string) {
  // Implement throttled ring-buffer or useSyncExternalStore here
  const [ticks, setTicks] = useState<TelemetryTick[]>([]);

  return { ticks };
}`,
      questionId: "q-4",
      allowedLanguages: ["typescript", "javascript", "python", "java", "cpp"],
    },
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: true,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: true,
    notes: "Lead technical architect round focusing on React 19 concurrent features and ring-buffer telemetry ingestion.",
    timeline: [
      { stage: "Created", timestamp: "2026-09-12 09:15", description: "Interview scheduled by Marcus Sterling" },
      { stage: "Scheduled", timestamp: "2026-09-12 09:16", description: "Calendar invites and secure tokens dispatched" },
      { stage: "Candidate Joined", timestamp: "2026-09-15 11:28", description: "Maya Chen completed audio & webcam telemetry check" },
      { stage: "Interview Started", timestamp: "2026-09-15 11:30", description: "Session in active live progress" },
    ],
  },
  {
    id: "int-today-2",
    candidateId: "cand-9",
    candidateName: "Hanna Lindqvist",
    candidateEmail: "hanna.l@nordictech.se",
    candidateAvatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    jobRole: "Senior Frontend Engineer (Design Systems)",
    interviewType: "Frontend Architecture",
    date: "2026-09-15", // Today
    time: "15:00",
    durationMinutes: 45,
    status: "Scheduled",
    interviewerId: "usr-interviewer-1",
    interviewerName: "Marcus Sterling",
    interviewerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    token: "HL492T",
    tokenExpiresAt: "2026-09-15T17:00:00Z",
    candidateLink: "https://app.veritrust.ai/interview/HL492T",
    codingRoundConfig: {
      language: "typescript",
      starterCode: `// Problem: Accessible Multi-Select Dropdown with ARIA 1.2
export function AccessibleMultiSelect() {
  return <div>Implement Accessible MultiSelect</div>;
}`,
      questionId: "q-9",
      allowedLanguages: ["typescript", "javascript"],
    },
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: true,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: true,
    timeline: [
      { stage: "Created", timestamp: "2026-09-13 14:20", description: "Interview created by Sarah Lin" },
      { stage: "Scheduled", timestamp: "2026-09-13 14:22", description: "Candidate token active" },
      { stage: "Reminder Sent", timestamp: "2026-09-14 10:00", description: "Calendar invite sent to candidate" },
      { stage: "Upcoming", timestamp: "2026-09-15 15:00", description: "Interview starts in 2 hours" },
    ],
  },
  {
    id: "int-tomorrow-1",
    candidateId: "cand-7",
    candidateName: "Sofia Rodriguez",
    candidateEmail: "s.rodriguez@techrio.br",
    candidateAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    jobRole: "Data Platform Engineer",
    interviewType: "Distributed Systems",
    date: "2026-09-16", // Tomorrow
    time: "10:00",
    durationMinutes: 60,
    status: "Scheduled",
    interviewerId: "usr-admin-1",
    interviewerName: "Dr. Elena Vance",
    interviewerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    token: "SR903K",
    tokenExpiresAt: "2026-09-16T12:00:00Z",
    candidateLink: "https://app.veritrust.ai/interview/SR903K",
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: true,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: true,
    timeline: [
      { stage: "Created", timestamp: "2026-09-14 10:00", description: "Scheduled follow-up technical screen" },
    ],
  },
  {
    id: "int-tomorrow-2",
    candidateId: "cand-1",
    candidateName: "Alexei Petrov",
    candidateEmail: "alexei.petrov@devcraft.io",
    candidateAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    jobRole: "Senior Distributed Systems Engineer",
    interviewType: "Distributed Systems",
    date: "2026-09-16", // Tomorrow
    time: "14:00",
    durationMinutes: 60,
    status: "Scheduled",
    interviewerId: "usr-admin-1",
    interviewerName: "Dr. Elena Vance",
    interviewerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    token: "AP712X",
    tokenExpiresAt: "2026-09-16T16:00:00Z",
    candidateLink: "https://app.veritrust.ai/interview/AP712X",
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: true,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: true,
    timeline: [
      { stage: "Created", timestamp: "2026-09-14 11:30", description: "Executive leadership alignment interview" },
    ],
  },
  {
    id: "int-week-1",
    candidateId: "cand-4",
    candidateName: "Amina Al-Mansoor",
    candidateEmail: "amina.mansoor@techfrontier.ae",
    candidateAvatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80",
    jobRole: "AI / ML Infrastructure Specialist",
    interviewType: "Distributed Systems",
    date: "2026-09-17",
    time: "11:00",
    durationMinutes: 45,
    status: "Scheduled",
    interviewerId: "usr-interviewer-1",
    interviewerName: "Marcus Sterling",
    interviewerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    token: "AM551Z",
    tokenExpiresAt: "2026-09-17T13:00:00Z",
    candidateLink: "https://app.veritrust.ai/interview/AM551Z",
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: true,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: true,
    timeline: [{ stage: "Created", timestamp: "2026-09-13 16:00", description: "Round 2 System Architecture" }],
  },
  {
    id: "int-week-2",
    candidateId: "cand-6",
    candidateName: "Liam O'Connor",
    candidateEmail: "liam.oconnor@dublin-eng.ie",
    candidateAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    jobRole: "Backend Engineer",
    interviewType: "Backend Engineering",
    date: "2026-09-18",
    time: "16:00",
    durationMinutes: 60,
    status: "Scheduled",
    interviewerId: "usr-interviewer-1",
    interviewerName: "Marcus Sterling",
    interviewerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    token: "LO883Q",
    tokenExpiresAt: "2026-09-18T18:00:00Z",
    candidateLink: "https://app.veritrust.ai/interview/LO883Q",
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: true,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: true,
    timeline: [{ stage: "Created", timestamp: "2026-09-14 09:00", description: "Security review scheduled" }],
  },
  {
    id: "int-later-1",
    candidateId: "cand-10",
    candidateName: "Kenji Sato",
    candidateEmail: "kenji.sato@tokyo-swe.jp",
    candidateAvatar: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80",
    jobRole: "Backend & Concurrency Specialist",
    interviewType: "Algorithms & Data Structures",
    date: "2026-09-22",
    time: "09:30",
    durationMinutes: 60,
    status: "Scheduled",
    interviewerId: "usr-admin-1",
    interviewerName: "Dr. Elena Vance",
    interviewerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    token: "KS104M",
    tokenExpiresAt: "2026-09-22T12:00:00Z",
    candidateLink: "https://app.veritrust.ai/interview/KS104M",
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: true,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: true,
    timeline: [{ stage: "Created", timestamp: "2026-09-14 12:00", description: "Advanced Concurrency Interview" }],
  },
  {
    id: "int-draft-1",
    candidateId: "cand-8",
    candidateName: "Tariq Hassan",
    candidateEmail: "tariq.hassan@cloudscale.net",
    candidateAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    jobRole: "DevOps & Cloud Architect",
    interviewType: "Distributed Systems",
    date: "2026-09-24",
    time: "13:00",
    durationMinutes: 45,
    status: "Draft",
    interviewerId: "usr-viewer-1",
    interviewerName: "Sarah Lin",
    interviewerAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    token: "TH992D",
    tokenExpiresAt: "2026-09-24T15:00:00Z",
    candidateLink: "https://app.veritrust.ai/interview/TH992D",
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: false,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: false,
    timeline: [{ stage: "Created", timestamp: "2026-09-15 08:30", description: "Draft created pending interviewer confirmation" }],
  },
  // Completed Interviews
  {
    id: "int-1",
    candidateId: "cand-1",
    candidateName: "Alexei Petrov",
    candidateEmail: "alexei.petrov@devcraft.io",
    candidateAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    jobRole: "Senior Distributed Systems Engineer",
    interviewType: "Distributed Systems",
    date: "2026-09-14",
    time: "14:00",
    durationMinutes: 60,
    status: "Completed",
    interviewerId: "usr-interviewer-1",
    interviewerName: "Marcus Sterling",
    interviewerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    token: "AP881X",
    tokenExpiresAt: "2026-09-14T16:00:00Z",
    candidateLink: "https://app.veritrust.ai/interview/AP881X",
    reportId: "rep-1",
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: true,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: true,
    timeline: [
      { stage: "Created", timestamp: "2026-09-10 11:00", description: "Interview created" },
      { stage: "Scheduled", timestamp: "2026-09-10 11:05", description: "Token generated" },
      { stage: "Candidate Joined", timestamp: "2026-09-14 13:58", description: "Candidate entered room" },
      { stage: "Interview Started", timestamp: "2026-09-14 14:00", description: "Session started" },
      { stage: "Interview Completed", timestamp: "2026-09-14 15:02", description: "Session ended by interviewer" },
      { stage: "Report Generated", timestamp: "2026-09-14 15:05", description: "Report rep-1 ready" },
    ],
  },
  {
    id: "int-2",
    candidateId: "cand-3",
    candidateName: "Devon Thorne",
    candidateEmail: "dthorne.codes@gmail.com",
    candidateAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    jobRole: "Senior Backend Engineer (High Throughput)",
    interviewType: "Algorithms & Data Structures",
    date: "2026-09-10",
    time: "11:00",
    durationMinutes: 45,
    status: "Completed",
    interviewerId: "usr-interviewer-1",
    interviewerName: "Marcus Sterling",
    interviewerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    token: "DT332V",
    tokenExpiresAt: "2026-09-10T13:00:00Z",
    candidateLink: "https://app.veritrust.ai/interview/DT332V",
    reportId: "rep-2",
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: true,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: true,
    timeline: [
      { stage: "Created", timestamp: "2026-09-08 09:00", description: "Interview created" },
      { stage: "Interview Started", timestamp: "2026-09-10 11:00", description: "Session conducted" },
      { stage: "Interview Completed", timestamp: "2026-09-10 11:47", description: "Session ended" },
      { stage: "Report Generated", timestamp: "2026-09-10 11:50", description: "Report rep-2 ready for review" },
    ],
  },
  {
    id: "int-3",
    candidateId: "cand-2",
    candidateName: "Maya Chen",
    candidateEmail: "maya.chen@alum.mit.edu",
    candidateAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    jobRole: "Lead Full Stack Architect",
    interviewType: "Frontend Architecture",
    date: "2026-09-12",
    time: "15:00",
    durationMinutes: 60,
    status: "Completed",
    interviewerId: "usr-interviewer-1",
    interviewerName: "Marcus Sterling",
    interviewerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    token: "MC449F",
    tokenExpiresAt: "2026-09-12T17:00:00Z",
    candidateLink: "https://app.veritrust.ai/interview/MC449F",
    reportId: "rep-3",
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: true,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: true,
    timeline: [
      { stage: "Created", timestamp: "2026-09-09 10:00", description: "Interview created" },
      { stage: "Interview Completed", timestamp: "2026-09-12 16:01", description: "Session completed" },
      { stage: "Report Generated", timestamp: "2026-09-12 16:04", description: "Report rep-3 ready" },
    ],
  },
  {
    id: "int-4",
    candidateId: "cand-4",
    candidateName: "Amina Al-Mansoor",
    candidateEmail: "amina.mansoor@techfrontier.ae",
    candidateAvatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80",
    jobRole: "AI / ML Infrastructure Specialist",
    interviewType: "Distributed Systems",
    date: "2026-09-08",
    time: "10:00",
    durationMinutes: 60,
    status: "Completed",
    interviewerId: "usr-admin-1",
    interviewerName: "Dr. Elena Vance",
    interviewerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    token: "AM201B",
    tokenExpiresAt: "2026-09-08T12:00:00Z",
    candidateLink: "https://app.veritrust.ai/interview/AM201B",
    reportId: "rep-4",
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: true,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: true,
    timeline: [
      { stage: "Interview Completed", timestamp: "2026-09-08 11:02", description: "Session ended" },
      { stage: "Report Generated", timestamp: "2026-09-08 11:05", description: "Report rep-4 ready" },
    ],
  },
  {
    id: "int-5",
    candidateId: "cand-5",
    candidateName: "Kavita Ramachandran",
    candidateEmail: "kavita.rama@protonmail.com",
    candidateAvatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    jobRole: "Principal Frontend Engineer",
    interviewType: "Frontend Architecture",
    date: "2026-09-05",
    time: "14:00",
    durationMinutes: 45,
    status: "Completed",
    interviewerId: "usr-interviewer-1",
    interviewerName: "Marcus Sterling",
    interviewerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    token: "KR782P",
    tokenExpiresAt: "2026-09-05T16:00:00Z",
    candidateLink: "https://app.veritrust.ai/interview/KR782P",
    reportId: "rep-5",
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: true,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: true,
    timeline: [
      { stage: "Interview Completed", timestamp: "2026-09-05 14:48", description: "Session ended" },
      { stage: "Report Generated", timestamp: "2026-09-05 14:50", description: "Report rep-5 ready" },
    ],
  },
  {
    id: "int-6",
    candidateId: "cand-6",
    candidateName: "Liam O'Connor",
    candidateEmail: "liam.oconnor@dublin-eng.ie",
    candidateAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    jobRole: "Senior Security & Platform Engineer",
    interviewType: "Backend Engineering",
    date: "2026-09-03",
    time: "13:00",
    durationMinutes: 60,
    status: "Completed",
    interviewerId: "usr-admin-1",
    interviewerName: "Dr. Elena Vance",
    interviewerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    token: "LO391L",
    tokenExpiresAt: "2026-09-03T15:00:00Z",
    candidateLink: "https://app.veritrust.ai/interview/LO391L",
    reportId: "rep-6",
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: true,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: true,
    timeline: [
      { stage: "Interview Completed", timestamp: "2026-09-03 14:02", description: "Session ended" },
      { stage: "Report Generated", timestamp: "2026-09-03 14:05", description: "Report rep-6 ready" },
    ],
  },
  {
    id: "int-7",
    candidateId: "cand-8",
    candidateName: "Tariq Hassan",
    candidateEmail: "tariq.hassan@cloudscale.net",
    candidateAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    jobRole: "DevOps & Cloud Architect",
    interviewType: "Distributed Systems",
    date: "2026-08-28",
    time: "15:30",
    durationMinutes: 60,
    status: "Completed",
    interviewerId: "usr-interviewer-1",
    interviewerName: "Marcus Sterling",
    interviewerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    token: "TH112O",
    tokenExpiresAt: "2026-08-28T17:30:00Z",
    candidateLink: "https://app.veritrust.ai/interview/TH112O",
    reportId: "rep-7",
    monitoringConfig: {
      webcamRequired: true,
      screenShareRequired: true,
      clipboardTracking: true,
      gazeTelemetry: true,
      audioAnalysis: true,
    },
    recordingEnabled: true,
    timeline: [
      { stage: "Interview Completed", timestamp: "2026-08-28 16:30", description: "Session ended" },
      { stage: "Report Generated", timestamp: "2026-08-28 16:33", description: "Report rep-7 ready" },
    ],
  },
];
