import { Report } from "../types";

export const MOCK_REPORTS: Report[] = [
  {
    id: "rep-1",
    interviewId: "int-1",
    candidateId: "cand-1",
    candidateName: "Alexei Petrov",
    candidateAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Senior Distributed Systems Engineer",
    interviewDate: "2026-09-14",
    interviewerName: "Marcus Sterling",
    status: "Approved",
    overallScore: 89,
    technicalScore: 92,
    communicationScore: 88,
    problemSolvingScore: 90,
    integrityConfidenceScore: 94,
    integrityBand: "High Confidence",
    integrityExplanation: "Multimodal behavioral signals demonstrate high baseline stability. Eye contact was natural and consistent with single-monitor coding. Keystroke flight times followed standard organic cognitive distribution. Zero correlated anomaly clusters detected.",
    correlatedAnomaliesCount: 0,
    aiSummary: "Alexei demonstrated exceptional technical mastery of distributed consensus protocols and leader election nuances. His reasoning when navigating network partitions was articulate, pragmatic, and grounded in production experience at scale.",
    keyStrengths: [
      "Flawless implementation of Raft log compaction and heartbeat timeouts",
      "Immediate recognition of split-brain edge cases and quorum math",
      "Clear, transparent communication while drafting concurrent unit tests",
    ],
    areasForImprovement: [
      "Could incorporate more proactive telemetry logging into the initial code draft rather than adding it as an afterthought",
    ],
    recommendation: "Strong Hire",
    recommendationReasoning: "Senior staff-level systems acumen combined with organic, highly confident problem decomposition. Unanimous interviewer endorsement.",
    questionEvaluations: [
      {
        id: "qe-1",
        questionId: "q-2",
        questionTitle: "Design a Distributed Rate Limiter (Token Bucket / Sliding Window)",
        candidateAnswerSummary: "Proposed Redis cluster with sliding window logs executed via atomic Lua script. Highlighted local token bucket caching to absorb transient spikes without saturating network sockets.",
        expectedReasoning: "Atomic sliding window or token bucket algorithm with race condition mitigation and failure degradation.",
        aiEvaluation: "Candidate displayed mastery over distributed locking alternatives, explicitly rejecting heavy distributed locks in favor of atomic Redis script evaluations.",
        score: 95,
        timeSpentMinutes: 28,
        codeQualityRating: "Exceptional",
      },
      {
        id: "qe-2",
        questionId: "q-6",
        questionTitle: "Implement a Thread-Safe In-Memory Key-Value Store",
        candidateAnswerSummary: "Partitioned the key space into 32 striped buckets, each protected by an independent RWMutex. Demonstrated lock contention reduction benchmark calculations.",
        expectedReasoning: "Striped/sharded locking to allow concurrent reads and localized writes.",
        aiEvaluation: "Flawless Go/C++ memory semantics. Addressed cache line bouncing and lock contention with precision.",
        score: 91,
        timeSpentMinutes: 24,
        codeQualityRating: "Exceptional",
      },
    ],
    integrityEvidence: [
      {
        id: "evt-1",
        timestamp: "00:03:12",
        timestampSeconds: 192,
        type: "Question change",
        severity: "Info",
        title: "Session Initialized & Baseline Established",
        description: "Initial webcam face registration calibrated. Stable pupil telemetry and microphone acoustic baseline recorded.",
      },
      {
        id: "evt-2",
        timestamp: "00:14:45",
        timestampSeconds: 885,
        type: "Code execution",
        severity: "Info",
        title: "Test Suite Executed",
        description: "Candidate ran custom unit tests. All 4 concurrent race detector assertions passed cleanly.",
      },
      {
        id: "evt-3",
        timestamp: "00:26:10",
        timestampSeconds: 1570,
        type: "Code execution",
        severity: "Info",
        title: "Final Verification Run",
        description: "Final benchmarks completed with zero deadlocks detected.",
      },
    ],
    interviewerNotes: "Superb candidate. Alexei did not hesitate to draw clear diagrams and explained trade-offs between memory footprint and lock contention.",
  },
  {
    id: "rep-2",
    interviewId: "int-2",
    candidateId: "cand-3",
    candidateName: "Devon Thorne",
    candidateAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Senior Backend Engineer (High Throughput)",
    interviewDate: "2026-09-10",
    interviewerName: "Marcus Sterling",
    status: "Pending Review",
    overallScore: 74,
    technicalScore: 76,
    communicationScore: 70,
    problemSolvingScore: 72,
    integrityConfidenceScore: 68,
    integrityBand: "Review Recommended",
    integrityExplanation: "Correlated behavioral anomalies were observed between minute 08:31 and 08:42. A large insertion of 185 formatted characters coincided with a 4-second lateral gaze deviation and an abrupt reduction in response latency. Human review of video snapshot and code diff is recommended to determine whether external notes were consulted.",
    correlatedAnomaliesCount: 4,
    aiSummary: "Devon displayed adequate knowledge of database indexes and HTTP service structures, but exhibited significant variance in coding pacing. A sudden influx of complex helper logic occurred without preceding verbalization.",
    keyStrengths: [
      "Understands SQL query explain plans and composite indexes",
      "Polite and professional demeanor throughout the session",
    ],
    areasForImprovement: [
      "Explain logic continuously while coding rather than operating in prolonged silence",
      "Explain the origin of helper abstractions when introducing large code chunks",
    ],
    recommendation: "Needs Further Review",
    recommendationReasoning: "Multimodal behavioral anomaly detected at minute 08:31. Interviewer should inspect the correlated evidence timeline before making a final offer determination.",
    questionEvaluations: [
      {
        id: "qe-3",
        questionId: "q-1",
        questionTitle: "Implement an LRU Cache with O(1) Operations",
        candidateAnswerSummary: "Began with a naive array search, then abruptly transitioned to a fully implemented Doubly Linked List with sentinel nodes following an extended pause.",
        expectedReasoning: "Hash map + doubly linked list node pointers for O(1) get and put.",
        aiEvaluation: "Solution is technically correct, but the transition from struggling with basic pointer manipulation to writing a fully optimized sentinel list was discontinuous.",
        score: 75,
        timeSpentMinutes: 32,
        codeQualityRating: "Adequate",
      },
    ],
    integrityEvidence: [
      {
        id: "evt-pdf-1",
        timestamp: "00:14:32",
        timestampSeconds: 872,
        type: "Gaze deviation",
        severity: "High",
        title: "Sustained Off-Screen Gaze & Correlated Audio",
        description: "Sustained off-screen gaze while a second voice was audible in the room.",
        correlatedGroupId: "corr-1",
        contextData: {
          gazeAngle: "42° Off-Axis",
          gazeDurationSeconds: 5.8,
        },
      },
      {
        id: "evt-4",
        timestamp: "00:08:31",
        timestampSeconds: 511,
        type: "Large code insertion",
        severity: "High",
        title: "Large Code Insertion Detected",
        description: "185 characters inserted within 120ms (equivalent to 1,540 WPM). Character flight time variance was < 2ms, indicating clipboard or external paste mechanism.",
        correlatedGroupId: "corr-1",
        contextData: {
          charactersInserted: 185,
          codeSnippet: "class Node { constructor(k, v) { this.k = k; this.v = v; this.prev = null; this.next = null; } }",
        },
      },
      {
        id: "evt-5",
        timestamp: "00:08:35",
        timestampSeconds: 515,
        type: "Gaze deviation",
        severity: "Medium",
        title: "Lateral Off-Screen Gaze Deviation",
        description: "Candidate eyes deviated 38 degrees to the bottom-right for 4.2 consecutive seconds immediately preceding code insertion.",
        correlatedGroupId: "corr-1",
        contextData: {
          gazeAngle: "38° Bottom-Right",
          gazeDurationSeconds: 4.2,
        },
      },
      {
        id: "evt-6",
        timestamp: "00:08:38",
        timestampSeconds: 518,
        type: "Unusual latency",
        severity: "Low",
        title: "Response Latency Shift",
        description: "Vocal response latency transitioned from 2,400ms baseline to instantaneous response without cognitive pause.",
        correlatedGroupId: "corr-1",
        contextData: {
          latencyMs: 180,
        },
      },
      {
        id: "evt-7",
        timestamp: "00:08:42",
        timestampSeconds: 522,
        type: "Code execution",
        severity: "Info",
        title: "Code Execution Triggered",
        description: "Inserted helper code compiled cleanly on first execution run.",
        correlatedGroupId: "corr-1",
      },
      {
        id: "evt-8",
        timestamp: "00:22:15",
        timestampSeconds: 1335,
        type: "Window blur",
        severity: "Low",
        title: "Browser Focus Lost",
        description: "Candidate browser tab lost window focus for 1.8 seconds before returning.",
      },
    ],
    interviewerNotes: "Noticed Devon looking off to his second screen right before the LRU linked list helper code appeared. When I asked him to explain the sentinel node logic, he gave a somewhat rehearsed answer. Recommending a short follow-up technical screen.",
  },
  {
    id: "rep-3",
    interviewId: "int-3",
    candidateId: "cand-2",
    candidateName: "Maya Chen",
    candidateAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Lead Full Stack Architect",
    interviewDate: "2026-09-12",
    interviewerName: "Marcus Sterling",
    status: "Approved",
    overallScore: 92,
    technicalScore: 94,
    communicationScore: 93,
    problemSolvingScore: 91,
    integrityConfidenceScore: 96,
    integrityBand: "High Confidence",
    integrityExplanation: "Exemplary behavioral baseline consistency. Candidate continuously thought out loud, paired live keystrokes with audible explanations, and maintained natural focal centering. Zero anomalies flagged.",
    correlatedAnomaliesCount: 0,
    aiSummary: "Maya delivered a standout interview. She solved high-frequency React re-render bottlenecks using a custom ring-buffer with useSyncExternalStore, walking through the React 19 reconciliation algorithm in depth.",
    keyStrengths: [
      "Mastery of modern React concurrency and server component data fetching",
      "Proactive consideration of memory consumption and GC pressure",
      "Natural leadership cadence and collaborative rapport",
    ],
    areasForImprovement: [
      "None observed; ready for Staff/Lead tier responsibility",
    ],
    recommendation: "Strong Hire",
    recommendationReasoning: "Top 1% candidate for the Full Stack Architect position. Perfect balance of low-level performance intuition and high-level system empathy.",
    questionEvaluations: [
      {
        id: "qe-4",
        questionId: "q-4",
        questionTitle: "Optimizing React Re-renders in High-Frequency Telemetry Dashboard",
        candidateAnswerSummary: "Decoupled WebSocket state updates from React render cycle using useSyncExternalStore with requestAnimationFrame micro-batching. Added windowed virtualization for 50k telemetry items.",
        expectedReasoning: "External store subscription, RAF batching, DOM virtualization.",
        aiEvaluation: "Solution achieved a locked 60 FPS under synthetic 300 ticks/sec load. Reasoning was airtight.",
        score: 96,
        timeSpentMinutes: 30,
        codeQualityRating: "Exceptional",
      },
    ],
    integrityEvidence: [
      {
        id: "evt-9",
        timestamp: "00:01:05",
        timestampSeconds: 65,
        type: "Question change",
        severity: "Info",
        title: "Session Calibrated",
        description: "Candidate video feed stable at 1080p 30fps. Verified single screen display topology.",
      },
      {
        id: "evt-10",
        timestamp: "00:19:40",
        timestampSeconds: 1180,
        type: "Code execution",
        severity: "Info",
        title: "Live Virtualization Benchmark Passed",
        description: "Candidate executed memory profiler script; 0 dropped frames recorded.",
      },
    ],
    interviewerNotes: "One of the best React interviews I have ever witnessed. Maya is a natural hire.",
  },
  {
    id: "rep-4",
    interviewId: "int-4",
    candidateId: "cand-4",
    candidateName: "Amina Al-Mansoor",
    candidateAvatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80",
    appliedRole: "AI / ML Infrastructure Specialist",
    interviewDate: "2026-09-08",
    interviewerName: "Dr. Elena Vance",
    status: "Approved",
    overallScore: 94,
    technicalScore: 98,
    communicationScore: 90,
    problemSolvingScore: 95,
    integrityConfidenceScore: 91,
    integrityBand: "High Confidence",
    integrityExplanation: "All behavioral metrics remained well within expected natural ranges. High technical authenticity validated through spontaneous whiteboarding of GPU memory bandwidth constraints.",
    correlatedAnomaliesCount: 0,
    aiSummary: "Amina demonstrated world-class mastery of GPU CUDA kernel memory coalescing and KV cache paging for LLMs. Her mathematical derivations were exact.",
    keyStrengths: [
      "Deep understanding of hardware memory hierarchies (HBM3e vs SRAM)",
      "Wrote Triton kernel pseudo-code with clear flash-attention scaling rationale",
    ],
    areasForImprovement: [
      "Could broaden familiarity with standard web API layer orchestration",
    ],
    recommendation: "Strong Hire",
    recommendationReasoning: "Essential addition for our inference acceleration roadmap.",
    questionEvaluations: [
      {
        id: "qe-5",
        questionId: "q-19",
        questionTitle: "Architecting an AI Agent Guardrail and Moderation Gateway",
        candidateAnswerSummary: "Designed speculative streaming token verification using a lightweight quantized model running alongside generation to achieve < 25ms latency penalty.",
        expectedReasoning: "Streaming token parsing, embedding classifiers, latency budgeting.",
        aiEvaluation: "Brilliant analysis of Time To First Token (TTFT) trade-offs vs safety buffer window sizes.",
        score: 97,
        timeSpentMinutes: 35,
        codeQualityRating: "Exceptional",
      },
    ],
    integrityEvidence: [
      {
        id: "evt-11",
        timestamp: "00:00:30",
        timestampSeconds: 30,
        type: "Question change",
        severity: "Info",
        title: "Session Started",
        description: "High-resolution telemetry stream active.",
      },
    ],
    interviewerNotes: "Phenomenal domain knowledge. Elena Vance strongly endorses.",
  },
  {
    id: "rep-5",
    interviewId: "int-5",
    candidateId: "cand-5",
    candidateName: "Kavita Ramachandran",
    candidateAvatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Principal Frontend Engineer",
    interviewDate: "2026-09-05",
    interviewerName: "Marcus Sterling",
    status: "Approved",
    overallScore: 96,
    technicalScore: 97,
    communicationScore: 96,
    problemSolvingScore: 94,
    integrityConfidenceScore: 98,
    integrityBand: "High Confidence",
    integrityExplanation: "Complete alignment across all behavioral telemetry channels. Exemplary transparent coding behavior.",
    correlatedAnomaliesCount: 0,
    aiSummary: "Kavita implemented an accessible combobox component completely from scratch, demonstrating flawless handling of ARIA attributes, keyboard traps, and virtual focus announcements.",
    keyStrengths: [
      "Industry-leading accessibility expertise",
      "Rapid, elegant TypeScript component architecture",
    ],
    areasForImprovement: ["None"],
    recommendation: "Strong Hire",
    recommendationReasoning: "Exceptional frontend leader. Candidate was extended an offer.",
    questionEvaluations: [
      {
        id: "qe-6",
        questionId: "q-9",
        questionTitle: "Building an Accessible Multi-Select Dropdown from Scratch",
        candidateAnswerSummary: "Built robust WAI-ARIA 1.2 compliant combobox with roving tabIndex, home/end key support, and live region announcer.",
        expectedReasoning: "Keyboard focus management, aria-controls, aria-activedescendant.",
        aiEvaluation: "Exceeded standard expectations by handling touch device and screen reader voiceover edge cases.",
        score: 98,
        timeSpentMinutes: 26,
        codeQualityRating: "Exceptional",
      },
    ],
    integrityEvidence: [
      {
        id: "evt-12",
        timestamp: "00:02:10",
        timestampSeconds: 130,
        type: "Question change",
        severity: "Info",
        title: "Question Initialized",
        description: "Candidate began drafting accessible state machine.",
      },
    ],
    interviewerNotes: "Hired. Candidate accepted offer on September 8th.",
  },
  {
    id: "rep-6",
    interviewId: "int-6",
    candidateId: "cand-6",
    candidateName: "Liam O'Connor",
    candidateAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Senior Security & Platform Engineer",
    interviewDate: "2026-09-03",
    interviewerName: "Dr. Elena Vance",
    status: "Approved",
    overallScore: 85,
    technicalScore: 88,
    communicationScore: 82,
    problemSolvingScore: 85,
    integrityConfidenceScore: 92,
    integrityBand: "High Confidence",
    integrityExplanation: "Telemetry indicates steady, focused problem formulation. No suspicious clipboard or gaze behavior recorded.",
    correlatedAnomaliesCount: 0,
    aiSummary: "Liam analyzed the security architecture of a multi-tenant webhook dispatcher, outlining threat vectors including SSRF, timing attacks, and replay vulnerabilities.",
    keyStrengths: [
      "Methodical zero-trust threat modeling",
      "Defensive coding practices in Rust and Go",
    ],
    areasForImprovement: [
      "Could move slightly faster through high-level boilerplate code",
    ],
    recommendation: "Hire",
    recommendationReasoning: "Strong security mindset that will safeguard our multi-tenant infrastructure.",
    questionEvaluations: [
      {
        id: "qe-7",
        questionId: "q-7",
        questionTitle: "Design a Scalable Webhook Delivery Engine",
        candidateAnswerSummary: "Proposed egress proxy with DNS rebinding protection, HMAC-SHA256 request signing, and jittered exponential retry queues.",
        expectedReasoning: "SSRF prevention, HMAC signing, dead-letter queue isolation.",
        aiEvaluation: "Thorough security analysis. Specifically highlighted internal RFC1918 IP blocklists to avoid cloud metadata exfiltration.",
        score: 89,
        timeSpentMinutes: 38,
        codeQualityRating: "Good",
      },
    ],
    integrityEvidence: [
      {
        id: "evt-13",
        timestamp: "00:00:45",
        timestampSeconds: 45,
        type: "Question change",
        severity: "Info",
        title: "Session Calibrated",
        description: "Zero anomalous video artifacts detected.",
      },
    ],
    interviewerNotes: "Solid security platform candidate. Good communicator.",
  },
  {
    id: "rep-7",
    interviewId: "int-7",
    candidateId: "cand-8",
    candidateName: "Tariq Hassan",
    candidateAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    appliedRole: "DevOps & Cloud Architect",
    interviewDate: "2026-08-28",
    interviewerName: "Marcus Sterling",
    status: "Approved",
    overallScore: 91,
    technicalScore: 92,
    communicationScore: 93,
    problemSolvingScore: 89,
    integrityConfidenceScore: 95,
    integrityBand: "High Confidence",
    integrityExplanation: "Normal behavioral telemetry throughout the session.",
    aiSummary: "Tariq designed a resilient multi-region Kubernetes failover strategy with automated Route53 DNS health checks and stateful database replication.",
    keyStrengths: [
      "Deep experience with Terraform modular state and drift detection",
      "Clear disaster recovery RTO/RPO calculation clarity",
    ],
    areasForImprovement: [
      "Familiarity with emerging Cilium eBPF service mesh features",
    ],
    recommendation: "Strong Hire",
    recommendationReasoning: "Clear hire for the cloud platform leadership vacancy.",
    correlatedAnomaliesCount: 0,
    questionEvaluations: [
      {
        id: "qe-8",
        questionId: "q-12",
        questionTitle: "Zero-Downtime Database Schema Migration Strategy",
        candidateAnswerSummary: "Detailed expand/contract migration protocol using dual writes and asynchronous backfills with shadow reading verification.",
        expectedReasoning: "Expand-contract pattern, concurrent indexing, lock mitigation.",
        aiEvaluation: "Accurately noted ACCESS EXCLUSIVE lock risks in Postgres and used lock_timeout safeguards.",
        score: 92,
        timeSpentMinutes: 28,
        codeQualityRating: "Exceptional",
      },
    ],
    integrityEvidence: [],
    interviewerNotes: "Tariq has great operational instincts. Would trust him with production keys.",
  },
  {
    id: "rep-8",
    interviewId: "int-8",
    candidateId: "cand-10",
    candidateName: "Kenji Sato",
    candidateAvatar: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Backend & Concurrency Specialist",
    interviewDate: "2026-08-20",
    interviewerName: "Marcus Sterling",
    status: "Approved",
    overallScore: 88,
    technicalScore: 93,
    communicationScore: 82,
    problemSolvingScore: 90,
    integrityConfidenceScore: 93,
    integrityBand: "High Confidence",
    integrityExplanation: "Clean behavioral baseline. Fluent low-level code generation with organic pacing.",
    correlatedAnomaliesCount: 0,
    aiSummary: "Kenji demonstrated exceptional insight into hardware cache coherence protocols and lock-free atomic pointer exchanges.",
    keyStrengths: [
      "Outstanding understanding of memory fences and CAS loops in C++",
    ],
    areasForImprovement: [
      "Could articulate business context alongside low-level technical trade-offs",
    ],
    recommendation: "Hire",
    recommendationReasoning: "High-value domain specialist for low-latency engine team.",
    questionEvaluations: [
      {
        id: "qe-9",
        questionId: "q-6",
        questionTitle: "Implement a Thread-Safe In-Memory Key-Value Store",
        candidateAnswerSummary: "Implemented lock-free skip list using atomic compare-and-swap nodes with hazard pointers for safe memory reclamation.",
        expectedReasoning: "Concurrent access patterns, memory models, synchronization.",
        aiEvaluation: "Extremely impressive grasp of memory ordering (acquire-release semantics).",
        score: 94,
        timeSpentMinutes: 32,
        codeQualityRating: "Exceptional",
      },
    ],
    integrityEvidence: [],
    interviewerNotes: "Kenji is an exceptional low-level engineer. Recommended for the core team.",
  },
  {
    id: "rep-9",
    interviewId: "int-9",
    candidateId: "cand-7",
    candidateName: "Sofia Rodriguez",
    candidateAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Data Platform Engineer",
    interviewDate: "2026-09-01",
    interviewerName: "Sarah Lin",
    status: "Pending Review",
    overallScore: 78,
    technicalScore: 80,
    communicationScore: 78,
    problemSolvingScore: 76,
    integrityConfidenceScore: 88,
    integrityBand: "Moderate Variance",
    integrityExplanation: "Minor telemetry variance: 2 brief tab blurs recorded during question reading. However, no correlated code insertion or gaze anomaly occurred.",
    correlatedAnomaliesCount: 1,
    aiSummary: "Sofia performed well on batch SQL optimization and schema star-modelling. She showed some hesitation when answering streaming Kafka windowing questions.",
    keyStrengths: [
      "Good SQL execution plan comprehension",
      "Clear communication of ETL pipeline error handling",
    ],
    areasForImprovement: [
      "Needs more exposure to real-time Apache Flink / Spark Streaming architectures",
    ],
    recommendation: "Needs Further Review",
    recommendationReasoning: "Borderline technical score on streaming requirements. Suggesting a second technical screen.",
    questionEvaluations: [
      {
        id: "qe-10",
        questionId: "q-3",
        questionTitle: "Detecting Cycle in Directed Graph & Topological Sort",
        candidateAnswerSummary: "Implemented Kahn's BFS algorithm with in-degree array to identify task dependency execution order.",
        expectedReasoning: "Graph modeling, Kahn's algorithm or DFS cycle check.",
        aiEvaluation: "Clean implementation with proper handling of disconnected DAG components.",
        score: 82,
        timeSpentMinutes: 22,
        codeQualityRating: "Good",
      },
    ],
    integrityEvidence: [
      {
        id: "evt-14",
        timestamp: "00:04:18",
        timestampSeconds: 258,
        type: "Window blur",
        severity: "Low",
        title: "Temporary Window Blur",
        description: "Browser tab blur detected for 3.1 seconds. No clipboard activity recorded.",
      },
    ],
    interviewerNotes: "Sofia is promising. Recommend scheduling second round focused on streaming.",
  },
  {
    id: "rep-10",
    interviewId: "int-10",
    candidateId: "cand-9",
    candidateName: "Hanna Lindqvist",
    candidateAvatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    appliedRole: "Senior Frontend Engineer (Design Systems)",
    interviewDate: "2026-08-25",
    interviewerName: "Sarah Lin",
    status: "Approved",
    overallScore: 82,
    technicalScore: 84,
    communicationScore: 86,
    problemSolvingScore: 78,
    integrityConfidenceScore: 95,
    integrityBand: "High Confidence",
    integrityExplanation: "Normal baseline metrics throughout the design systems interview.",
    correlatedAnomaliesCount: 0,
    aiSummary: "Hanna designed a flexible design token system with CSS custom properties, automated dark mode contrast validation, and atomic typography scales.",
    keyStrengths: [
      "Strong aesthetic sensibility and attention to typography details",
      "Collaborative and open to constructive feedback",
    ],
    areasForImprovement: [
      "Could strengthen theoretical knowledge of canvas and WebGL performance",
    ],
    recommendation: "Hire",
    recommendationReasoning: "Strong candidate for our design systems and frontend component guild.",
    questionEvaluations: [
      {
        id: "qe-11",
        questionId: "q-9",
        questionTitle: "Building an Accessible Multi-Select Dropdown from Scratch",
        candidateAnswerSummary: "Focused on keyboard navigation and focus rings, ensuring high-contrast compliance for both light and dark themes.",
        expectedReasoning: "Keyboard access, focus management, semantic ARIA roles.",
        aiEvaluation: "Well-structured component with clean separation of styling tokens.",
        score: 85,
        timeSpentMinutes: 24,
        codeQualityRating: "Good",
      },
    ],
    integrityEvidence: [],
    interviewerNotes: "Hanna showed great passion for UI design tokens and micro-interactions.",
  },
];
